apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
      app: mysql
  template:
    metadata:
      labels:
        name: mysql
        app: mysql



    spec:
      containers:
        - name: container-mysql
          image: mysql:5.5
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              value: "loja"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          volumeMounts:
            - name: volume-mysql
              mountPath: /var/lib/mysql


      volumes:
       - name: volume-mysql
         persistentVolumeClaim:
           claimName: configuracao-mysql
